---
include:
  - board: xiao_ble//zmk
    shield: charybdis_dual_dongle
    artifact-name: charybdis_dongle

  - board: xiao_ble//zmk
    shield: charybdis_dual_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: charybdis_left

  - board: xiao_ble//zmk
    shield: charybdis_dual_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: charybdis_right
