CONFIG_ZMK_POINTING=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# Layer 0 = BLUE
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=240
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100

# さっき確認した暗さ
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=2
