CONFIG_ZMK_POINTING=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# 2 = SPECTRUM
# 赤→黄→緑→水色→青→紫→赤…と連続して変化
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2

# 一番ゆっくり
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=1

CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100

# 今気に入っている暗さ
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=2


# Trackball BLE receive queue test
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=32
